### ISSUE TITLE
Windows 10 Update 

### ISSUE THREAD

**Issue by Eziken** [changeofpace/MouClassInputInjection#1]
Hello and thanks for releasing your work! 

May I know what it needs to be updated to get this working for Windows 10, please?
![image](https://user-images.githubusercontent.com/52371494/61513717-aa961900-aa06-11e9-81cb-063a11358756.png)

**Comment by changeofpace** [comment]
The heuristic could be failing for several reasons.

I do not know if four MouHid device objects is standard for Windows 10. Are you using any third party mouse drivers? e.g., A Logitech driver which lets you control the LED colors of your mouse.

Try increasing `DEVICE_EXTENSION_SEARCH_SIZE` in `mouhid.cpp` to something like 0x200. If you have experience with IDA Pro then I can direct you to the function which has the actual field offset.

If this does not fix the error then I will need to setup a Windows 10 vm to debug this.

**Comment by RRSync** [comment]
Totally forgot to uninstall oblitum's Interception drivers! 

![image](https://user-images.githubusercontent.com/13313305/61593412-d91f1a00-abe7-11e9-9e68-269bcfaa9fde.png)

**Comment by Eziken** [comment]
I forgot to uninstall oblitum's Interception drivers!  Thank you for help!

![image](https://user-images.githubusercontent.com/52371494/61593430-0bc91280-abe8-11e9-891b-d78ec4870ba5.png)
