### ISSUE TITLE
Unable to load driver

### ISSUE THREAD

**Issue by RBJRBJ** [changeofpace/MouClassInputInjection#3]
Trying the MouClassInputInjection on Win 10, built with VS2019:

C:\Users\WDKRemoteUser\Desktop\kbtest>\drivertest\devcon install \drivertest\drivers\mouclassinputinjection.inf HID_DEVICE_SYSTEM_MOUSE
Device node created. Install is complete when drivers are installed...
Updating drivers for HID_DEVICE_SYSTEM_MOUSE from C:\drivertest\drivers\mouclassinputinjection.inf.
devcon failed.

C:\Users\WDKRemoteUser\Desktop\kbtest>MouiiCL.exe
MouiiIoInitialization failed: 2

Not sure if INF file is correct. Remote deploy gives some errors. See same issue with MouHidInputHook...

**Comment by changeofpace** [comment]
Try loading the driver using `sc.exe` or a driver loader like https://github.com/tandasat/DrvLoader. The driver is not signed so the target environment needs to have test signing enabled.

**Comment by koreguy** [comment]
Hi, I'm having the same problem as well. what's the correct way to install this?
