### ISSUE TITLE
Inject Mouse Input Data To Non-Interactive Desktop?

### ISSUE THREAD

**Issue by msdn77** [changeofpace/MouClassInputInjection#7]
Hello,

Let's say i have DesktopA and DesktopB.
On DesktopB i have mspaint.exe running, DesktopB is not active now(non-interactive).

It would be possible to send mouse input if i specify ProcessId=mspaint.exe which is on DesktopB, while active desktop is DesktopA?

Thanks

**Comment by msdn77** [comment]
Just tested the driver and seems that it's not possible :(
Clicks are sent to current interactive desktop(DesktopA) even if i specify proccessid from DesktopB.
Btw, is there a way to send mouse inputs to non-interactive DesktopB. 
Maybe You can tell me where to dig?

Many thanks

**Comment by changeofpace** [comment]
@msdn77

I don't know if you can send mouse data to other desktops. You could look at the following functions from win32k.sys (Windows 7):

- ProcessMouseInput
- RegisterForDeviceChangeNotifications
- StartDeviceRead
- InputApc
- xxxDesktopThread
