### ISSUE TITLE
MhdDriverEntry failed 0xC0000034

### ISSUE THREAD

**Issue by Narumiiii** [changeofpace/MouClassInputInjection#9]
Hello i am unable to load the driver it fails on MhdDriver entry with the status code **0xC0000034** wich is **STATUS_OBJECT_NAME_NOT_FOUND**  and before on **ObReferenceObjectByName failed 0xC0000034** seems like it can't find the device of mouhid.sys but mouhid is running any solution to this?

**Comment by changeofpace** [comment]
What architecture, windows version, and build number are you seeing this on?

Are you running this in a VM?

**Comment by Narumiiii** [comment]
> What architecture, windows version, and build number are you seeing this on?
> 
> Are you running this in a VM?

I did all tests on Windows 10 x64 from build 1904 to 2004, this error can appears if you aren't using a hid mouse (like a touchpad) but i was using it ever the only solution i found was doing a clean install of my system and it worked, are any alternative to this? or any way to solve that, because i tried a lot in the time i had that issue and i never solved it, thanks.

**Comment by changeofpace** [comment]
I'm not sure what type of device a touchpad gets mapped to, but if it is not a HID class then this technique will not work. You may be able to to port the hooking strategy to other mouse device types.
